/*
 * lib/quran.js — the app's single Quran API.
 *
 * HARD RULES (do not break these when editing):
 *   • Every number this module exposes comes from lib/quran-data.js, which is
 *     generated by scripts/build-quran-data.mjs from the pinned sources in
 *     data/sources/ (QCF4/QPC Hafs mushaf layout + Tanzil metadata, cross-checked
 *     against the Quran.com API). Nothing here is guessed or estimated.
 *   • Ayah identity is EXACT and canonical: an ayah is addressed by its global
 *     number (1..6236) in mushaf order, or by (surah, ayah) with the surah's real
 *     ayah count enforced. Invalid input THROWS — it is never clamped, snapped or
 *     silently reduced (that is what produced wrong ranges before).
 *   • Ranges are always inclusive sets of complete ayahs [fromG..toG]. A range can
 *     therefore never start or end in the middle of an ayah, never exceed a
 *     surah's ayah count, and never be printed in the wrong order.
 *   • Quarter-faces (¼ وجه) are only an accounting unit for how much work a day
 *     holds; the ayah span stays the source of truth.
 */

import DATA from './quran-data.js';

export const META = DATA.meta;
export const SURAHS = DATA.surahs; // [{n,name,count,startAyah,page,lastPage,qStart,qEnd,bismillah}]
export const TOTAL_AYAHS = DATA.meta.totalAyahs; // 6236
export const QPP = DATA.meta.quartersPerPage; // 4 quarter-faces per face (=per page)
export const TOTAL_Q = DATA.meta.totalQuarters; // 2416
export const TOTAL_PAGES = DATA.meta.pages; // 604

const AYAH_Q = DATA.ayahQ; // 6236 quarter-face starts, index 0 = 1:1
const AYAH_PAGE = DATA.ayahPage;
const AYAH_LINE = DATA.ayahLine;

/* ---------------- fast lookups (built once, from the generated data) ------- */
const SURAH_FIRST = new Array(115).fill(0); // surah -> global ayah (1-based) of ayah 1
const SURAH_OF = new Uint8Array(TOTAL_AYAHS + 1);
const NO_IN_SURAH = new Uint16Array(TOTAL_AYAHS + 1);
for (const s of SURAHS) {
  SURAH_FIRST[s.n] = s.startAyah;
  for (let a = 1; a <= s.count; a++) {
    SURAH_OF[s.startAyah + a - 1] = s.n;
    NO_IN_SURAH[s.startAyah + a - 1] = a;
  }
}

/* ---------------- surahs --------------------------------------------------- */
export function surahByNumber(n) {
  const x = Number(n);
  if (!Number.isInteger(x) || x < 1 || x > 114)
    throw new RangeError(`سورة غير موجودة: ${n} — المصحف فيه ١١٤ سورة فقط`);
  return SURAHS[x - 1];
}
export function surahName(n) {
  return surahByNumber(n).name;
}
export function ayahCount(n) {
  return surahByNumber(n).count;
}

/* ---------------- ayah identity ------------------------------------------- */
/** global ayah number (1..6236) of (surah, ayah); throws on any invalid pair */
export function globalAyah(surah, ayah) {
  const s = surahByNumber(surah);
  const a = Number(ayah);
  if (!Number.isInteger(a) || a < 1 || a > s.count)
    throw new RangeError(
      `سورة ${s.name} فيها ${arNum(s.count)} ${s.count >= 3 && s.count <= 10 ? 'آيات' : 'آية'} فقط — الآية ${arNum(Number.isFinite(a) ? a : 0)} غير موجودة`
    );
  return s.startAyah + a - 1;
}

/** {surah, ayah, name, page, q, qEnd} for a global ayah number */
export function ayahRef(g) {
  assertGlobalAyah(g);
  const surah = SURAH_OF[g];
  const ayah = NO_IN_SURAH[g];
  return {
    g,
    surah,
    ayah,
    name: SURAHS[surah - 1].name,
    page: AYAH_PAGE[g - 1],
    line: AYAH_LINE[g - 1],
    q: ayahQStart(g),
    qEnd: ayahQEnd(g),
  };
}

/** "الفلق ٥" / "٢:٢٥٥" style short reference */
export function ayahKey(g) {
  const r = ayahRef(g);
  return `${r.surah}:${r.ayah}`;
}
export const surahOfAyah = (g) => ayahRef(g).surah;

export function assertGlobalAyah(g) {
  const x = Number(g);
  if (!Number.isInteger(x) || x < 1 || x > TOTAL_AYAHS)
    throw new RangeError(`رقم آية غير صحيح: ${g} — ترتيب الآيات في المصحف من ١ إلى ${arNum(TOTAL_AYAHS)}`);
  return x;
}

/* ---------------- quarter-face positions ---------------------------------- */
export function ayahQStart(g) {
  return AYAH_Q[assertGlobalAyah(g) - 1];
}
export function ayahQEnd(g) {
  const x = assertGlobalAyah(g);
  return x < TOTAL_AYAHS ? AYAH_Q[x] : TOTAL_Q; // next ayah starts where this span ends
}
/** length of one ayah in quarter-faces (≥1) */
export function ayahSpanQ(g) {
  const x = assertGlobalAyah(g);
  return ayahQEnd(x) - ayahQStart(x) || 1;
}
/** exact quarter-face length of an inclusive ayah range */
export function rangeQ(gFrom, gTo) {
  const { lo, hi } = normRange(gFrom, gTo);
  return ayahQEnd(hi) - ayahQStart(lo);
}
export function ayahPage(g) {
  return AYAH_PAGE[assertGlobalAyah(g) - 1];
}
export function ayahLine(g) {
  return AYAH_LINE[assertGlobalAyah(g) - 1];
}

/* ---------------- ranges -------------------------------------------------- */
function normRange(gFrom, gTo) {
  const a = assertGlobalAyah(gFrom);
  const b = assertGlobalAyah(gTo);
  return { lo: Math.min(a, b), hi: Math.max(a, b), from: a, to: b, dir: b >= a ? 1 : -1 };
}

/** validated inclusive range: {fromG,toG,lo,hi,q,direction,surahFrom,surahTo,ayahCount} */
export function makeRange(gFrom, gTo) {
  const r = normRange(gFrom, gTo);
  const a = ayahRef(r.from);
  const b = ayahRef(r.to);
  return {
    fromG: r.from,
    toG: r.to,
    lo: r.lo,
    hi: r.hi,
    q: rangeQ(r.lo, r.hi),
    direction: r.dir > 0 ? 'asc' : 'desc',
    surahFrom: a.surah,
    surahTo: b.surah,
    ayahCount: r.hi - r.lo + 1,
  };
}

/** {ok, errors[]} — never throws; used by the UI before it accepts user input */
export function validateRange(gFrom, gTo) {
  const errors = [];
  const a = Number(gFrom);
  const b = Number(gTo);
  if (!Number.isInteger(a) || a < 1 || a > TOTAL_AYAHS)
    errors.push(`بداية غير صحيحة: ${gFrom} — ترتيب الآيات من ١ إلى ${arNum(TOTAL_AYAHS)}`);
  if (!Number.isInteger(b) || b < 1 || b > TOTAL_AYAHS)
    errors.push(`نهاية غير صحيحة: ${gTo} — ترتيب الآيات من ١ إلى ${arNum(TOTAL_AYAHS)}`);
  return { ok: errors.length === 0, errors };
}

export function assertValidRange(gFrom, gTo) {
  const v = validateRange(gFrom, gTo);
  if (!v.ok) throw new RangeError(v.errors.join(' · '));
  return makeRange(gFrom, gTo);
}

/** the whole mushaf, or any surah span, as a validated range in mushaf order */
export function surahSpanRange(fromSurah, toSurah) {
  const a = surahByNumber(fromSurah);
  const b = surahByNumber(toSurah);
  return { loG: Math.min(a.startAyah, b.startAyah), hiG: Math.max(a.startAyah + a.count - 1, b.startAyah + b.count - 1) };
}

/** (surah, ayah) → (surah, ayah) range, validated with Arabic error messages */
export function rangeFromSurahAyah(s1, a1, s2 = s1, a2 = a1) {
  const loG = globalAyah(s1, a1);
  const hiG = globalAyah(s2, a2);
  return makeRange(loG, hiG);
}

/** first ayah of the surah that contains g, last ayah of it, etc. */
export function surahBoundsOf(g) {
  const r = ayahRef(g);
  const s = SURAHS[r.surah - 1];
  return { firstG: s.startAyah, lastG: s.startAyah + s.count - 1, surah: s.n, name: s.name, count: s.count };
}

/* ---------------- day splitting (always complete ayahs) ------------------- */
/**
 * Last ayah of the chunk that starts at gStart, travelling in `dir` and holding
 * at most doseQ quarter-faces — but always at least one whole ayah, and never
 * past gLimit. Complete ayahs only: an ayah is never cut in half, so two
 * consecutive chunks always meet exactly at an ayah boundary.
 */
export function splitDose(gStart, gLimit, doseQ, dir = 1) {
  const start = assertGlobalAyah(gStart);
  const limit = assertGlobalAyah(gLimit);
  const step = dir < 0 ? -1 : 1;
  if (step > 0 ? start > limit : start < limit) return null; // nothing left in this direction
  const dose = Math.max(1, Math.round(Number(doseQ) || 0));
  const startQ = ayahQStart(start);
  const endQ = ayahQEnd(start);
  // geometric length of the contiguous ayah run [start..g] (or [g..start] descending)
  const lenOf = (g) => (step > 0 ? ayahQEnd(g) - startQ : endQ - ayahQStart(g));
  let last = start;
  for (let g = start; step > 0 ? g <= limit : g >= limit; g += step) {
    const len = lenOf(g);
    if (len > dose && g !== start) break; // this ayah would overflow the day's dose
    last = g;
    if (len >= dose) break;
  }
  return last;
}

export const nextAyah = (g, dir = 1) => assertGlobalAyah(g) + (dir < 0 ? -1 : 1);

/* ---------------- labels (exact, never guessed) --------------------------- */
/**
 * Human label for an inclusive ayah range.
 * @returns {{head,detail,cross,sameSurah,from,to,inRangeSurahEnds,inRangeSurahStarts,lastAyahOfMushaf}}
 *   head   — «الفلق» or «الناس ← الفلق» (travel order)
 *   detail — «الآيات ١ – ٥» or «من الفلق آية ٥ إلى الناس آية ١»
 */
export function rangeLabel(gFrom, gTo) {
  const r = normRange(gFrom, gTo);
  const a = ayahRef(r.from);
  const b = ayahRef(r.to);
  const lo = ayahRef(r.lo);
  const hi = ayahRef(r.hi);
  const cross = a.surah !== b.surah;
  // surah boundaries touched by the range (mushaf order)
  const ends = [];
  for (let s = lo.surah; s <= hi.surah; s++) {
    const su = SURAHS[s - 1];
    const lastG = su.startAyah + su.count - 1;
    if (lastG >= r.lo && lastG <= r.hi) ends.push({ surah: s, name: su.name, ayah: su.count, g: lastG });
  }
  const starts = [];
  for (let s = lo.surah; s <= hi.surah; s++) {
    const su = SURAHS[s - 1];
    if (su.startAyah >= r.lo && su.startAyah <= r.hi) starts.push({ surah: s, name: su.name, ayah: 1, g: su.startAyah });
  }
  const single = r.lo === r.hi;
  return {
    head: cross ? `${a.name} ← ${b.name}` : a.name,
    detail: cross
      ? `من ${a.name} آية ${arNum(a.ayah)} إلى ${b.name} آية ${arNum(b.ayah)}`
      : single
        ? `الآية ${arNum(a.ayah)}`
        : `الآيات ${arNum(lo.ayah)} – ${arNum(hi.ayah)}`,
    cross,
    sameSurah: !cross,
    single,
    from: { surah: a.surah, ayah: a.ayah, name: a.name, g: a.g },
    to: { surah: b.surah, ayah: b.ayah, name: b.name, g: b.g },
    inRangeSurahEnds: ends, // ranges that finish a surah (الفلق ٥ …)
    inRangeSurahStarts: starts, // ranges that open a surah (… الناس ١)
    lastAyahOfMushaf: r.hi === TOTAL_AYAHS,
  };
}

/* ---------------- legacy migration (old quarter-based pins) --------------- */
/**
 * The old (buggy) model stored manual pins as quarter-face spans {qLo,qHi}.
 * Convert one to the exact complete-ayah range it intended — or return null when
 * it cannot be mapped unambiguously (nothing is guessed: an unmappable pin is
 * dropped, never approximated).
 */
export function legacyRangeFromQuarters(qLo, qHi) {
  const lo = Number(qLo);
  const hi = Number(qHi);
  if (!Number.isFinite(lo) || !Number.isFinite(hi) || hi <= lo) return null;
  if (lo < 0 || hi > TOTAL_Q) return null;
  // A quarter-face boundary can be shared by several ayahs (a short ayah does
  // not always get a quarter of its own: 1721 of the 2416 boundaries are
  // shared). Mapping therefore only succeeds when the old span lands EXACTLY on
  // one single ayah's first quarter and one single ayah's last quarter; any
  // other span is ambiguous and is dropped — never rounded, never guessed.
  const startsAt = [];
  for (let g = 1; g <= TOTAL_AYAHS; g++) {
    const q = ayahQStart(g);
    if (q === lo) startsAt.push(g);
    else if (q > lo) break;
  }
  const endsAt = [];
  for (let g = TOTAL_AYAHS; g >= 1; g--) {
    const q = ayahQEnd(g);
    if (q === hi) endsAt.push(g);
    else if (q < hi) break;
  }
  if (startsAt.length !== 1 || endsAt.length !== 1) return null;
  const gFrom = startsAt[0];
  const gTo = endsAt[0];
  if (gTo < gFrom) return null;
  return makeRange(gFrom, gTo);
}

/* ---------------- Arabic-friendly formatting ------------------------------ */
const DIGITS = '\u0660\u0661\u0662\u0663\u0664\u0665\u0666\u0667\u0668\u0669';
export function arNum(x) {
  return String(x).replace(/\d/g, (d) => DIGITS[+d]);
}
/** decimal face count, e.g. 102.5 -> "١٠٢٫٥" */
export function arDec(x) {
  return arNum(Number(x.toFixed(2)).toString().replace('.', '٫'));
}

const REM_NAMES = { 1: 'ربع', 2: 'نصف', 3: 'ثلاثة أرباع' };
export function faceWord(w) {
  if (w === 1) return 'وجه';
  if (w === 2) return 'وجهان';
  if (w >= 3 && w <= 10) return `${arNum(w)} أوجه`;
  return `${arNum(w)} وجهًا`;
}
/** amount label from quarter-faces: q=5 -> "وجه وربع", q=2 -> "نصف وجه" */
export function amountLabel(q) {
  if (!q) return '—';
  const whole = Math.floor(q / QPP);
  const rem = q % QPP;
  if (!whole) return `${REM_NAMES[rem]} وجه`;
  return rem ? `${faceWord(whole)} و${REM_NAMES[rem]}` : faceWord(whole);
}

/** dropdown options for daily amounts (value = faces) */
export const AMOUNT_OPTS = [
  { v: 0.25, label: 'ربع وجه' },
  { v: 0.5, label: 'نصف وجه' },
  { v: 0.75, label: 'ثلاثة أرباع وجه' },
  { v: 1, label: 'وجه' },
  { v: 1.5, label: 'وجه ونصف' },
  { v: 2, label: 'وجهان' },
];
export const AMOUNT_OPTS_OPTIONAL = [{ v: 0, label: 'لا يوجد' }, ...AMOUNT_OPTS];
export const toQ = (faces) => Math.round(faces * QPP);
