/*
 * Generates data/quran.json from the QCF4 (Madinah Mushaf) dataset
 * (verses.json: verse -> page/line), matching Tanzil / Quran.com pagination.
 *
 * Unit model (as used on the official Tahfiz-association cards):
 *   1 page (صفحة) = 15 lines = 1 "wajh" (وجه) of the card vocabulary
 *   1 quarter-face (ربع وجه) = 1 quarter (ربْع) of a page = ~3.75 lines
 *   Whole mushaf = 604 pages = 2416 quarter-faces
 *
 * Run: npm run gen
 */
import fs from 'fs';

const LINES_PER_PAGE = 15;
const QUARTERS_PER_PAGE = 4;
const TOTAL_PAGES = 604;
const TOTAL_QUARTERS = TOTAL_PAGES * QUARTERS_PER_PAGE; // 2416

const verses = JSON.parse(fs.readFileSync('data/verses_raw.json', 'utf8'));
const index = JSON.parse(fs.readFileSync('data/index_raw.json', 'utf8'));

/** absolute quarter-face position (0-based) of a page/line */
function qOf(page, line) {
  const inPage = Math.max(0, Math.min(LINES_PER_PAGE - 1, line - 1));
  return (page - 1) * QUARTERS_PER_PAGE + Math.floor((inPage * QUARTERS_PER_PAGE) / LINES_PER_PAGE);
}

let totalAyahs = 0;
const surahs = index.chapters
  .slice()
  .sort((a, b) => a.id - b.id)
  .map((c) => {
    const qp = [];
    for (let i = 1; i <= c.verses_count; i++) {
      const e = verses[`${c.id}:${i}`];
      if (!e) throw new Error(`missing ayah ${c.id}:${i}`);
      qp.push(qOf(e.page, e.lines[0].line));
    }
    totalAyahs += c.verses_count;
    return {
      n: c.id,
      name: c.name_arabic,
      count: c.verses_count,
      page: verses[`${c.id}:1`].page,
      startQ: qp[0],
      qp,
    };
  });

// endQ: next surah's start (exact tiling); last surah ends at end of page 604
surahs.forEach((s, i) => {
  s.endQ = i + 1 < surahs.length ? surahs[i + 1].startQ : TOTAL_QUARTERS;
});

// sanity checks
if (surahs.length !== 114) throw new Error('expected 114 surahs');
if (totalAyahs !== 6236) throw new Error('expected 6236 ayahs, got ' + totalAyahs);
for (let i = 0; i < surahs.length; i++) {
  const s = surahs[i];
  for (let j = 1; j < s.qp.length; j++)
    if (s.qp[j] < s.qp[j - 1]) throw new Error(`non-monotonic positions in surah ${s.n}`);
  if (i > 0 && s.startQ < surahs[i - 1].startQ) throw new Error('surah starts not monotonic');
}

const ahqaf = surahs.find((s) => s.n === 46);
const nas = surahs.find((s) => s.n === 114);
const facesAhqafNas = (nas.endQ - ahqaf.startQ) / QUARTERS_PER_PAGE;

const out = {
  meta: {
    source: 'QCF4 Madinah Mushaf layout (verified against api.quran.com / Tanzil pagination)',
    pages: TOTAL_PAGES,
    linesPerPage: LINES_PER_PAGE,
    quartersPerPage: QUARTERS_PER_PAGE,
    totalQuarters: TOTAL_QUARTERS,
  },
  surahs,
};

fs.writeFileSync('data/quran.json', JSON.stringify(out));
// ESM module version so the same data can be imported by plain Node (tests) and webpack alike
fs.writeFileSync('lib/quran-data.js', '/* generated by scripts/gen-quran.mjs — do not edit */\nexport default ' + JSON.stringify(out) + ';\n');

console.log('OK -> data/quran.json');
console.log(`Al-Ahqaf starts page ${ahqaf.page} at quarter-face #${ahqaf.startQ} (0-based)`);
console.log(`Al-Ahqaf -> An-Nas = ${facesAhqafNas} faces (pages), = ${facesAhqafNas * 4} quarter-faces`);
console.log(`Al-Fatiha: ${surahs[0].name} p${surahs[0].page} q${surahs[0].startQ}..${surahs[0].endQ}`);
console.log(`An-Nas: endQ=${nas.endQ} (total quarters ${TOTAL_QUARTERS})`);
